import type { Metadata } from "next";
import SideBar from "./_components/SideBar";
import PlayBar from "./_components/PlayBar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
    <body>
      <div className="w-screen h-screen flex flex-col">
        <div className="w-full h-[90vh] flex-auto  flex ">
          <SideBar/>
          <div className="w-[80%] h-full ">{children}</div>
        </div>
        <PlayBar/>
      </div>
     </body>
   </html>
  );
};

export default Layout;
